services:
  mysql:
    container_name: mysql
    image: mysql:9
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=pVVSuX4KQ7w7nCqxTrYbmhTk3Z1ST7SZ
    restart: unless-stopped
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt/mosquitto:/etc/mosquitto
    restart: unless-stopped
  kma:
    container_name: kma
    image: 12build/keepmealive3d:1.0.0
    depends_on:
      - mysql
      - mqtt
    ports:
      - "80:8080"
    volumes:
      - ./kma/config.yml:/app/config.yml
      - ./kma/models:/app/models
    restart: unless-stopped

networks:
  default:
    driver: bridge