passphrase: 'Bpwh3aNH0rF6DsOOFmJ9xnYvyPPRGWDP'        # todo change passphrase
databases:
  sql:
    host: 'jdbc:mysql://localhost:3306/kma'
    user: 'root'
    password: 'pVVSuX4KQ7w7nCqxTrYbmhTk3Z1ST7SZ'      # todo change credentials (defined in mysql)
  sqlMigrate: # used to create the schema and tables needed, when initial migration is run, access can be restricted
    host: 'jdbc:mysql://localhost:3306'
    user: 'root'
    password: 'pVVSuX4KQ7w7nCqxTrYbmhTk3Z1ST7SZ'
  mqtt:
    host: 'localhost'
    port: 1883
    clientId: 'kma'
    password: 'Dii5BPSarVnENLMQU8RqIBa5e25djili'      # todo change credentials (defined in mqtt)
    topic: '#'
  influx:
    host: 'xxx'
    port: 8086
    org: 'xxx'
    bucket: 'xxx'
    token: 'xxx'
pluginDirs: ["plugins"]
