services:
  kma:
    container_name: kma
    image: 12build/keepmealive3d:latest
    volumes:
      - ./config.yml:/app/config.yml
      - ./models:/app/models
    environment:
      # reverse proxy
      VIRTUAL_HOST: kma.myhost.de     # todo enter the domain kma is running on
      LETSENCRYPT_HOST: kma.myhost.de # todo enter the domain kma is running on
      LETSENCRYPT_EMAIL: my@email.de  # todo enter a email for lets encrypt info
      VIRTUAL_PORT: 8080
      WEB_SOCKET_SUPPORT: true
    network_mode: bridge
